version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  jobs:
    pre_build:
      - sphinx-apidoc --force --module-first --separate --output-dir docs/source/api pelutils

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
