# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "tests",
    "examples",
]

line-length = 150
indent-width = 4

# Assume Python 3.9, as that is minimum supported version
target-version = "py39"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = [
    "E",  # pycodestyle errors
    "F",  # Pyflakes
    "B",  # flake8-bugbear
    "I",  # isort
    "D",  # pydocstyle
    "UP",  # pyupgrade
]
ignore = [
    "B024",  # No abstract methods
    "D100",  # Missing docstring in public module
    "D104",  # Missing docstring in public package
    "D105",  # Docstring in magic method
    "E402",  # Import not at top of file
]

[lint.pydocstyle]
convention = "numpy"
ignore-decorators = ["overload", "property"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]  # Unused imports
