name: pytest

on:
  push:
    branches: [ master, release ]
    paths:
        - pelutils/**.py
        - tests/**.py
        - .github/workflows

  pull_request:
    branches: [ master, release ]
    paths:
        - pelutils/**.py
        - tests/**.py
        - .github/workflows

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up PyPi dependencies and install package
        run: |
          pip install --upgrade setuptools wheel
          pip install numpy
          pip install -e .[tests]

      - name: Run test
        run: pytest --cov=pelutils

      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
