name: pytest

on:
  push:
    branches: [ master, develop ]
    paths:
        - pelutils/**.py
        - tests/**.py
        - Makefile
        - .github/workflows

  pull_request:
    branches: [ master, develop ]
    paths:
        - pelutils/**.py
        - tests/**.py
        - Makefile
        - .github/workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build C extensions
        shell: bash
        run: |
          git submodule update --init --recursive
          make clean && make

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up PyPi dependencies and install package
        run: |
          pip install --upgrade setuptools wheel
          pip install pytest-cov
          pip install -e .[ds]

      - name: Run test
        run: pytest --cov=pelutils
