name: pytest

on:
  push:
    branches: [ master, develop ]
    paths:
        - pelutils/**.py
        - tests/**.py
        - Makefile
        - .github/workflows
      
  pull_request:
    branches: [ master, develop ]
    paths:
        - pelutils/**.py
        - tests/**.py
        - Makefile
        - .github/workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up PyPi dependencies and install package
        run: |
          pip install pytest-cov
          pip install .[ds]

      - name: Run test
        run: pytest --cov=pelutils
